<?php

namespace ijony\yiis\yii2di\cm;

use yii\di\NotInstantiableException;

/**
 * 使用该类，替换了部分类的实现，方便YII项目的迁移
 *
 * @package ijony\yiis\yii2di
 */
class Container extends \yii\di\Container
{

    private static $_persistents = [];

    protected $autoReplace = true;

    private $classCompatible = [
        'yii\web\Request' => 'web\Request',
        'yii\web\Response' => 'web\Response',
        'yii\web\ErrorHandler' => 'web\ErrorHandler',
        'yii\log\Logger' => 'log\Logger',
        'yii\web\Session' => 'web\cm\Session',
        'yii\web\CacheSession' => 'web\cm\CacheSession',
        'yii\web\DbSession' => 'web\cm\DbSession',
        'yii\log\FileTarget' => 'log\FileTarget',
        'yii\db\Command' => 'db\Command',
        'yii\db\Connection' => 'db\cm\Connection',
        'yii\redis\Connection' => 'redis\cm\Connection',
        'yii\redis\Session' => 'redis\cm\Session',
    ];

    /**
     * 可以被持久化在内存的类
     *
     * @var array
     */
    private $classPersistent = [
        'web\Request',
        'web\Response',
        'web\cm\Session',
        'web\cm\CacheSession',
        'web\cm\DbSession',
        'redis\cm\Session',
        'log\Logger',
        'pool\ConnectionManager',
        'web\ErrorHandler',
        'yii\web\UrlManager',
        'yii\i18n\I18N',
    ];

    public function setAutoReload($value)
    {
        $this->autoReplace = $value;
    }

    public function get($class, $params = [], $config = [])
    {
        return parent::get($class, $params, $config); // TODO: Change the autogenerated stub
    }

    protected function build($class, $params, $config)
    {
        if ($this->autoReplace && isset($this->classCompatible[$class])) {
            $class = $this->classCompatible[$class];
        }
        if (in_array($class, $this->classPersistent)) {
            return $this->buildPersistent($class, $params, $config);
        }

        return parent::build($class, $params, $config); // TODO: Change the autogenerated stub
    }

    /**
     * 构建可持久化的类
     *
     * @param $class
     * @param $params
     * @param $config
     *
     * @return mixed|null|object
     * @throws NotInstantiableException
     */
    protected function buildPersistent($class, $params, $config)
    {
        $key = $this->buildKey($class, $params, $config);
        if (isset(self::$_persistents[$key])) {
            return self::$_persistents[$key];
        }
        $object = parent::build($class, $params, $config);
        self::$_persistents[$key] = $object;

        return $object;
    }

    /**
     * @param $class
     * @param $params
     * @param $config
     *
     * @return string
     */
    protected function buildKey($class, $params, $config)
    {
        return $class . md5(Container . phpjson_encode($params) . json_encode($config));
    }

}