<?php

namespace ijony\yiis\yii2di;

use yii\di\NotInstantiableException;

/**
 * 使用该类，替换了部分类的实现，方便YII项目的迁移
 *
 * @package ijony\yiis\yii2di
 */
class Container extends \yii\di\Container
{

    private static $_persistents = [];

    protected $autoReplace = true;

    private $classCompatible = [
        'yii\web\Request' => 'web\Request',
        'yii\web\Response' => 'web\Response',
        'yii\web\ErrorHandler' => 'web\ErrorHandler',
        'yii\log\Logger' => 'log\Logger',
        'yii\web\Session' => 'web\Session',
        'yii\web\CacheSession' => 'web\CacheSession',
        'yii\web\DbSession' => 'web\DbSession',
        'yii\log\FileTarget' => 'log\FileTarget',
        'yii\db\Command' => 'db\Command',
        'yii\db\Connection' => 'db\Connection',
        'yii\redis\Connection' => 'redis\Connection',
        'yii\redis\Cache' => 'redis\Cache',
        'yii\redis\Session' => 'redis\Session',
    ];

    /**
     * 可以被持久化在内存的类
     *
     * @var array
     */
    private $classPersistent = [
        'pool\ConnectionManager',
        'log\Logger',
        'web\ErrorHandler',
        'yii\web\UrlManager',
        'yii\i18n\I18N',
    ];

    public function setAutoReload($value)
    {
        $this->autoReplace = $value;
    }

    public function get($class, $params = [], $config = [])
    {
        return parent::get($class, $params, $config); // TODO: Change the autogenerated stub
    }

    protected function build($class, $params, $config)
    {
        if ($this->autoReplace && isset($this->classCompatible[$class])) {
            $class = $this->classCompatible[$class];
        }
        if (in_array($class, $this->classPersistent)) {
            return $this->buildPersistent($class, $params, $config);
        }

        return parent::build($class, $params, $config); // TODO: Change the autogenerated stub
    }

    /**
     * 构建可持久化的类
     *
     * @param $class
     * @param $params
     * @param $config
     *
     * @return mixed|null|object
     * @throws NotInstantiableException
     */
    protected function buildPersistent($class, $params, $config)
    {
        $key = $this->buildKey($class, $params, $config);
        if (isset(self::$_persistents[$key])) {
            return self::$_persistents[$key];
        }
        $object = $this->buildInSwoole($class, $params, $config);
        self::$_persistents[$key] = $object;

        return $object;
    }

    /**
     * @param $class
     * @param $params
     * @param $config
     *
     * @return string
     */
    protected function buildKey($class, $params, $config)
    {
        return $class . md5(Container . phpjson_encode($params) . json_encode($config));
    }

    /**
     * 原生Reflection反射构造时在swoole中存在冲突,需要重新处理
     *
     * @see https://github.com/swoole/swoole-src/issues/1020
     *
     * @param $class
     * @param $params
     * @param $config
     *
     * @return object
     * @throws NotInstantiableException
     */
    private function buildInSwoole($class, $params, $config)
    {
        /* @var $reflection \ReflectionClass */
        [$reflection, $dependencies] = $this->getDependencies($class);

        foreach ($params as $index => $param) {
            $dependencies[$index] = $param;
        }

        $dependencies = $this->resolveDependencies($dependencies, $reflection);
        if (!$reflection->isInstantiable()) {
            throw new NotInstantiableException($reflection->name);
        }
        if (empty($config)) {
            return $reflection->newInstanceArgs($dependencies);
        }

        if (!empty($dependencies) && $reflection->implementsInterface('yii\base\Configurable')) {
            $dependencies[count($dependencies) - 1] = $config;
            $instance = $reflection->newInstanceWithoutConstructor();
            call_user_func_array([$instance, '__construct'], $dependencies);

            return $instance;
        } else {
            $object = $reflection->newInstanceWithoutConstructor();
            call_user_func_array([$object, '__construct'], $dependencies);
            foreach ($config as $name => $value) {
                $object->$name = $value;
            }

            return $object;
        }
    }

}